name: CI/CD Pipeline with ZAP Scan

on:
  push:
    branches:
      - master

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Juice Shop Docker Image
        run: |
          docker build -t juice-shop .

      - name: Run Juice Shop container
        run: |
          # Run container in detached mode, mapping container port 3000 to host port 3000
          docker run -d --name juice-shop-container -p 3000:3000 juice-shop

      - name: Wait for Juice Shop to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:3000 | grep -i "juice"; then
              echo "Juice Shop is up!"
              exit 0
            fi
            echo "Waiting for Juice Shop to start..."
            sleep 2
          done
          echo "Juice Shop did not start in time"
          exit 1

      - name: Run ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          target: "http://localhost:3000"
          # -a runs all the active scan rules, and -j outputs JSON format (adjust options as needed)
          cmd_options: "-a -j"

      - name: Stop and remove Juice Shop container
        run: |
          docker stop juice-shop-container
          docker rm juice-shop-container

      - name: Upload ZAP report artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan
          path: zap-report.html